### PR TITLE
Support decorators

### PR DESCRIPTION
**Pull request by blueyed**
This is based on #9.

### CODE REVIEW

**Comment by bps** [comment]
Excellent — thanks! :+1:

Just curious: was `<esc>` causing a problem in the tests? (9705df9) I believe `'>` and `'<` should be set regardless.

**Comment by blueyed** [comment]
> Just curious: was <esc> causing a problem in the tests?

The existing tests worked, but it caused the current line to get changed, which I've noticed with the new tests that check for the line's content.

**Comment by bps** [comment]
Makes sense.

Thanks so much for all of these PRs!

**Comment by blueyed** [comment]
You're welcome.

**Pull request merged**
